name: Playwright Tests (Python)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: purple-guardian-playwright # <== chạy trong thư mục dự án thật của bạn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest playwright pytest-playwright

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run tests
        run: pytest -q
